version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm ci
      - npm install -g aws-cdk

  build:
    commands:
      - ls -la
      - unzip -o '*.zip' -d . || true
      - ls -la
      - cdk deploy --require-approval never --all

artifacts:
  files:
    - cdk.out/**/*