version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install -g aws-cdk

  build:
    commands:
      - cdk deploy --require-approval never --all --app cdk.out

artifacts:
  files:
    - cdk.out/**/*